### ISSUE TITLE
Things to improve

### ISSUE THREAD

**Issue by uniumuniu** [czescCi/uniumuniu-website#6]
- (This you can do at the end, as it may be related to the mobile version and / or create the most problems) When the window shrinks, at some point the sections should line up on top of each other and not next to each other. I think it can be done with flexbox. Now, you can narrow the window to such an extent that the text blends together and one of the sections is hidden.
- You probably didn't push the latest changes, because the 'about' section still has the logo on the right side, not at the top, above the text. Push and let me know.
- When 'about' is active, the right border of projects should be yellow. When the 'contact' is active,
the right border of 'about' should be yellow. Otherwise, everything should stay same as now. You can set 'border-color' to navy blue in 'resetAllDivs ()' and after click on 'about' or 'contact' change the border color of the relevant section.
- Please find free, white icons for 'contact' and 'projects'. For contact: an envelope, For projects: a pencil and a sheet of paper? Some standard ones. All sections at the start of the website should have a large, similar-looking logo. When activating the section, the logo should be there over the content. And with the collapsed section, it should be smaller and at the top (still thinking but it should be good enough for now).

**Comment by czescCi** [comment]
Need to work on border between nonactives sections.

**Comment by czescCi** [comment]
Please review
